// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  dungeonId: __t.u64().name("dungeon_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  x: __t.f32(),
  y: __t.f32(),
  radius: __t.f32(),
  healPerTick: __t.i32().name("heal_per_tick"),
  durationRemaining: __t.f32().name("duration_remaining"),
});
