// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("ActiveHealingZone", {
  id: __t.u64(),
  dungeonId: __t.u64(),
  ownerIdentity: __t.identity(),
  x: __t.f32(),
  y: __t.f32(),
  radius: __t.f32(),
  healPerTick: __t.i32(),
  durationRemaining: __t.f32(),
});


