// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("DungeonEnemy", {
  id: __t.u64(),
  dungeonId: __t.u64(),
  roomIndex: __t.u32(),
  enemyType: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  hp: __t.i32(),
  maxHp: __t.i32(),
  atk: __t.i32(),
  isAlive: __t.bool(),
  aiState: __t.string(),
  stateTimer: __t.f32(),
  targetX: __t.f32(),
  targetY: __t.f32(),
  facingAngle: __t.f32(),
  packId: __t.option(__t.u64()),
  currentTarget: __t.option(__t.string()),
  isTaunted: __t.bool(),
  tauntedBy: __t.option(__t.string()),
  tauntTimer: __t.f32(),
  isBoss: __t.bool(),
  bossPhase: __t.u32(),
});


