// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  dungeonId: __t.u64().name("dungeon_id"),
  roomIndex: __t.u32().name("room_index"),
  enemyType: __t.string().name("enemy_type"),
  x: __t.f32(),
  y: __t.f32(),
  hp: __t.i32(),
  maxHp: __t.i32().name("max_hp"),
  atk: __t.i32(),
  isAlive: __t.bool().name("is_alive"),
});
