// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.11.3 (commit 02449737ca3b29e7e39679fccbef541a50f32094).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import and reexport all reducer arg types
import AddInventoryItemReducer from "./add_inventory_item_reducer";
export { AddInventoryItemReducer };
import AttackReducer from "./attack_reducer";
export { AttackReducer };
import AttackOpenWorldReducer from "./attack_open_world_reducer";
export { AttackOpenWorldReducer };
import CancelQueueReducer from "./cancel_queue_reducer";
export { CancelQueueReducer };
import CompleteDungeonReducer from "./complete_dungeon_reducer";
export { CompleteDungeonReducer };
import DiscardItemReducer from "./discard_item_reducer";
export { DiscardItemReducer };
import EnterOpenWorldReducer from "./enter_open_world_reducer";
export { EnterOpenWorldReducer };
import EnterRoomReducer from "./enter_room_reducer";
export { EnterRoomReducer };
import EquipItemReducer from "./equip_item_reducer";
export { EquipItemReducer };
import LeaveOpenWorldReducer from "./leave_open_world_reducer";
export { LeaveOpenWorldReducer };
import LoginReducer from "./login_reducer";
export { LoginReducer };
import PickupLootReducer from "./pickup_loot_reducer";
export { PickupLootReducer };
import PlaceHealingZoneReducer from "./place_healing_zone_reducer";
export { PlaceHealingZoneReducer };
import QueueDungeonReducer from "./queue_dungeon_reducer";
export { QueueDungeonReducer };
import QueueRaidReducer from "./queue_raid_reducer";
export { QueueRaidReducer };
import RegisterPlayerReducer from "./register_player_reducer";
export { RegisterPlayerReducer };
import SendChatReducer from "./send_chat_reducer";
export { SendChatReducer };
import SendEmoteReducer from "./send_emote_reducer";
export { SendEmoteReducer };
import SetGameModeReducer from "./set_game_mode_reducer";
export { SetGameModeReducer };
import StartDungeonReducer from "./start_dungeon_reducer";
export { StartDungeonReducer };
import StartDungeonSoloReducer from "./start_dungeon_solo_reducer";
export { StartDungeonSoloReducer };
import TickEnemiesReducer from "./tick_enemies_reducer";
export { TickEnemiesReducer };
import TickMatchmakingReducer from "./tick_matchmaking_reducer";
export { TickMatchmakingReducer };
import TickOpenWorldReducer from "./tick_open_world_reducer";
export { TickOpenWorldReducer };
import UnequipItemReducer from "./unequip_item_reducer";
export { UnequipItemReducer };
import UpdateOpenWorldPositionReducer from "./update_open_world_position_reducer";
export { UpdateOpenWorldPositionReducer };
import UpdatePositionReducer from "./update_position_reducer";
export { UpdatePositionReducer };
import UseDashReducer from "./use_dash_reducer";
export { UseDashReducer };
import UseKnockbackReducer from "./use_knockback_reducer";
export { UseKnockbackReducer };
import UseTauntReducer from "./use_taunt_reducer";
export { UseTauntReducer };

// Import and reexport all procedure arg types

// Import and reexport all table handle types
import ActiveDungeonRow from "./active_dungeon_table";
export { ActiveDungeonRow };
import ActiveHealingZoneRow from "./active_healing_zone_table";
export { ActiveHealingZoneRow };
import DailyRaidClearRow from "./daily_raid_clear_table";
export { DailyRaidClearRow };
import DungeonEnemyRow from "./dungeon_enemy_table";
export { DungeonEnemyRow };
import DungeonParticipantRow from "./dungeon_participant_table";
export { DungeonParticipantRow };
import DungeonQueueRow from "./dungeon_queue_table";
export { DungeonQueueRow };
import EnemyTickScheduleRow from "./enemy_tick_schedule_table";
export { EnemyTickScheduleRow };
import InventoryItemRow from "./inventory_item_table";
export { InventoryItemRow };
import LootDropRow from "./loot_drop_table";
export { LootDropRow };
import MatchmakingTickScheduleRow from "./matchmaking_tick_schedule_table";
export { MatchmakingTickScheduleRow };
import OpenWorldEnemyRow from "./open_world_enemy_table";
export { OpenWorldEnemyRow };
import OpenWorldInstanceRow from "./open_world_instance_table";
export { OpenWorldInstanceRow };
import OpenWorldPlayerRow from "./open_world_player_table";
export { OpenWorldPlayerRow };
import OpenWorldTickScheduleRow from "./open_world_tick_schedule_table";
export { OpenWorldTickScheduleRow };
import PlayerRow from "./player_table";
export { PlayerRow };
import PlayerAbilityStateRow from "./player_ability_state_table";
export { PlayerAbilityStateRow };
import PlayerGameModeRow from "./player_game_mode_table";
export { PlayerGameModeRow };
import PlayerMessageRow from "./player_message_table";
export { PlayerMessageRow };
import PlayerPositionRow from "./player_position_table";
export { PlayerPositionRow };
import RaidCooldownRow from "./raid_cooldown_table";
export { RaidCooldownRow };
import RaidInstanceRow from "./raid_instance_table";
export { RaidInstanceRow };
import RaidParticipantRow from "./raid_participant_table";
export { RaidParticipantRow };
import RaidQueueRow from "./raid_queue_table";
export { RaidQueueRow };
import ThreatEntryRow from "./threat_entry_table";
export { ThreatEntryRow };

// Import and reexport all types
import ActiveDungeon from "./active_dungeon_type";
export { ActiveDungeon };
import ActiveHealingZone from "./active_healing_zone_type";
export { ActiveHealingZone };
import DailyRaidClear from "./daily_raid_clear_type";
export { DailyRaidClear };
import DungeonEnemy from "./dungeon_enemy_type";
export { DungeonEnemy };
import DungeonParticipant from "./dungeon_participant_type";
export { DungeonParticipant };
import DungeonQueue from "./dungeon_queue_type";
export { DungeonQueue };
import EnemyTickSchedule from "./enemy_tick_schedule_type";
export { EnemyTickSchedule };
import InventoryItem from "./inventory_item_type";
export { InventoryItem };
import LootDrop from "./loot_drop_type";
export { LootDrop };
import MatchmakingTickSchedule from "./matchmaking_tick_schedule_type";
export { MatchmakingTickSchedule };
import OpenWorldEnemy from "./open_world_enemy_type";
export { OpenWorldEnemy };
import OpenWorldInstance from "./open_world_instance_type";
export { OpenWorldInstance };
import OpenWorldPlayer from "./open_world_player_type";
export { OpenWorldPlayer };
import OpenWorldTickSchedule from "./open_world_tick_schedule_type";
export { OpenWorldTickSchedule };
import Player from "./player_type";
export { Player };
import PlayerAbilityState from "./player_ability_state_type";
export { PlayerAbilityState };
import PlayerGameMode from "./player_game_mode_type";
export { PlayerGameMode };
import PlayerMessage from "./player_message_type";
export { PlayerMessage };
import PlayerPosition from "./player_position_type";
export { PlayerPosition };
import RaidCooldown from "./raid_cooldown_type";
export { RaidCooldown };
import RaidInstance from "./raid_instance_type";
export { RaidInstance };
import RaidParticipant from "./raid_participant_type";
export { RaidParticipant };
import RaidQueue from "./raid_queue_type";
export { RaidQueue };
import ThreatEntry from "./threat_entry_type";
export { ThreatEntry };

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema(
  __table({
    name: 'active_dungeon',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'active_dungeon_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ActiveDungeonRow),
  __table({
    name: 'active_healing_zone',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'active_healing_zone_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ActiveHealingZoneRow),
  __table({
    name: 'daily_raid_clear',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'daily_raid_clear_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, DailyRaidClearRow),
  __table({
    name: 'dungeon_enemy',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'dungeon_enemy_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DungeonEnemyRow),
  __table({
    name: 'dungeon_participant',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'dungeon_participant_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DungeonParticipantRow),
  __table({
    name: 'dungeon_queue',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'dungeon_queue_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, DungeonQueueRow),
  __table({
    name: 'enemy_tick_schedule',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'enemy_tick_schedule_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, EnemyTickScheduleRow),
  __table({
    name: 'inventory_item',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'inventory_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, InventoryItemRow),
  __table({
    name: 'loot_drop',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'loot_drop_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LootDropRow),
  __table({
    name: 'matchmaking_tick_schedule',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'matchmaking_tick_schedule_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, MatchmakingTickScheduleRow),
  __table({
    name: 'open_world_enemy',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'open_world_enemy_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OpenWorldEnemyRow),
  __table({
    name: 'open_world_instance',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'open_world_instance_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OpenWorldInstanceRow),
  __table({
    name: 'open_world_player',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'open_world_player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, OpenWorldPlayerRow),
  __table({
    name: 'open_world_tick_schedule',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'open_world_tick_schedule_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, OpenWorldTickScheduleRow),
  __table({
    name: 'player',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  __table({
    name: 'player_ability_state',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_ability_state_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerAbilityStateRow),
  __table({
    name: 'player_game_mode',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_game_mode_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerGameModeRow),
  __table({
    name: 'player_message',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'player_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlayerMessageRow),
  __table({
    name: 'player_position',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_position_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerPositionRow),
  __table({
    name: 'raid_cooldown',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'raid_cooldown_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, RaidCooldownRow),
  __table({
    name: 'raid_instance',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'raid_instance_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RaidInstanceRow),
  __table({
    name: 'raid_participant',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'raid_participant_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RaidParticipantRow),
  __table({
    name: 'raid_queue',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'raid_queue_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, RaidQueueRow),
  __table({
    name: 'threat_entry',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'threat_entry_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ThreatEntryRow),
);

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_inventory_item", AddInventoryItemReducer),
  __reducerSchema("attack", AttackReducer),
  __reducerSchema("attack_open_world", AttackOpenWorldReducer),
  __reducerSchema("cancel_queue", CancelQueueReducer),
  __reducerSchema("complete_dungeon", CompleteDungeonReducer),
  __reducerSchema("discard_item", DiscardItemReducer),
  __reducerSchema("enter_open_world", EnterOpenWorldReducer),
  __reducerSchema("enter_room", EnterRoomReducer),
  __reducerSchema("equip_item", EquipItemReducer),
  __reducerSchema("leave_open_world", LeaveOpenWorldReducer),
  __reducerSchema("login", LoginReducer),
  __reducerSchema("pickup_loot", PickupLootReducer),
  __reducerSchema("place_healing_zone", PlaceHealingZoneReducer),
  __reducerSchema("queue_dungeon", QueueDungeonReducer),
  __reducerSchema("queue_raid", QueueRaidReducer),
  __reducerSchema("register_player", RegisterPlayerReducer),
  __reducerSchema("send_chat", SendChatReducer),
  __reducerSchema("send_emote", SendEmoteReducer),
  __reducerSchema("set_game_mode", SetGameModeReducer),
  __reducerSchema("start_dungeon", StartDungeonReducer),
  __reducerSchema("start_dungeon_solo", StartDungeonSoloReducer),
  __reducerSchema("tick_enemies", TickEnemiesReducer),
  __reducerSchema("tick_matchmaking", TickMatchmakingReducer),
  __reducerSchema("tick_open_world", TickOpenWorldReducer),
  __reducerSchema("unequip_item", UnequipItemReducer),
  __reducerSchema("update_open_world_position", UpdateOpenWorldPositionReducer),
  __reducerSchema("update_position", UpdatePositionReducer),
  __reducerSchema("use_dash", UseDashReducer),
  __reducerSchema("use_knockback", UseKnockbackReducer),
  __reducerSchema("use_taunt", UseTauntReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "1.11.3" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. */
export const tables = __convertToAccessorMap(tablesSchema.schemaType.tables);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

