// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("OpenWorldEnemy", {
  id: __t.u64(),
  instanceId: __t.u64(),
  roomX: __t.i32(),
  roomY: __t.i32(),
  spawnPointIdx: __t.u32(),
  enemyType: __t.string(),
  hp: __t.i32(),
  maxHp: __t.i32(),
  atk: __t.i32(),
  x: __t.f32(),
  y: __t.f32(),
  isAlive: __t.bool(),
  respawnAt: __t.u64(),
  aiState: __t.string(),
  stateTimer: __t.f32(),
  targetX: __t.f32(),
  targetY: __t.f32(),
  facingAngle: __t.f32(),
});


