// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  instanceId: __t.u64().name("instance_id"),
  roomX: __t.i32().name("room_x"),
  roomY: __t.i32().name("room_y"),
  x: __t.f32(),
  y: __t.f32(),
  facingX: __t.f32().name("facing_x"),
  facingY: __t.f32().name("facing_y"),
  name: __t.string(),
  level: __t.u32(),
  playerClass: __t.string().name("player_class"),
  weaponIcon: __t.string().name("weapon_icon"),
  armorIcon: __t.string().name("armor_icon"),
  accessoryIcon: __t.string().name("accessory_icon"),
});
