// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  instanceId: __t.u64().name("instance_id"),
  roomX: __t.i32().name("room_x"),
  roomY: __t.i32().name("room_y"),
  spawnPointIdx: __t.u32().name("spawn_point_idx"),
  enemyType: __t.string().name("enemy_type"),
  hp: __t.i32(),
  maxHp: __t.i32().name("max_hp"),
  atk: __t.i32(),
  x: __t.f32(),
  y: __t.f32(),
  isAlive: __t.bool().name("is_alive"),
  respawnAt: __t.u64().name("respawn_at"),
  aiState: __t.string().name("ai_state"),
  stateTimer: __t.f32().name("state_timer"),
  targetX: __t.f32().name("target_x"),
  targetY: __t.f32().name("target_y"),
  facingAngle: __t.f32().name("facing_angle"),
});
