// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("PlayerPosition", {
  identity: __t.identity(),
  dungeonId: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
  facingX: __t.f32(),
  facingY: __t.f32(),
  name: __t.string(),
  level: __t.u32(),
  weaponIcon: __t.string(),
  armorIcon: __t.string(),
  accessoryIcon: __t.string(),
});


