// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  playerClass: __t.string().name("player_class"),
  level: __t.u32(),
  xp: __t.u64(),
  hp: __t.i32(),
  maxHp: __t.i32().name("max_hp"),
  atk: __t.i32(),
  def: __t.i32(),
  speed: __t.i32(),
  gold: __t.u64(),
  dungeonsCleared: __t.u32().name("dungeons_cleared"),
});
