// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  dungeonId: __t.u64().name("dungeon_id"),
  tauntCd: __t.f32().name("taunt_cd"),
  knockbackCd: __t.f32().name("knockback_cd"),
  healingZoneCd: __t.f32().name("healing_zone_cd"),
  dashCd: __t.f32().name("dash_cd"),
  postDashBonusTimer: __t.f32().name("post_dash_bonus_timer"),
});
