// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("PlayerAbilityState", {
  identity: __t.identity(),
  dungeonId: __t.u64(),
  tauntCd: __t.f32(),
  knockbackCd: __t.f32(),
  healingZoneCd: __t.f32(),
  dashCd: __t.f32(),
  postDashBonusTimer: __t.f32(),
});


