// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("RaidInstance", {
  id: __t.u64(),
  startedAt: __t.u64(),
  bossHp: __t.i32(),
  bossMaxHp: __t.i32(),
  bossPhase: __t.u32(),
  wipeCount: __t.u32(),
});


